spring.application.name=ToDoOrNotToDo
# Server Port
server.port=8080

# PostgreSQL Verbindung
spring.datasource.url=jdbc:postgresql://localhost:5432/todoornottodo_db
spring.datasource.username=postgres
spring.datasource.password=#Simon300!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Caching
spring.cache.type=simple
spring.cache.cache-names=weatherCache

# DevTools / HTML Reload
spring.thymeleaf.cache=false